Update cloc.yml

diff --git a/.github/workflows/cloc.yml b/.github/workflows/cloc.yml
--- a/.github/workflows/cloc.yml
+++ b/.github/workflows/cloc.yml
@@ -23,8 +23,24 @@ jobs:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - uses: actions/checkout@v3
 
-      - name: Get the lines of code.
-        id: scc
-        uses: iryanbell/scc-docker-action@v1.0.2
+      - name: Count Lines Of Code
+        id: loc
+        run: |
+          curl -sLO https://github.com/vearutop/sccdiff/releases/download/v1.0.3/linux_amd64.tar.gz && tar xf linux_amd64.tar.gz
+          sccdiff_hash=$(git hash-object ./sccdiff)
+          [ "$sccdiff_hash" == "ae8a07b687bd3dba60861584efe724351aa7ff63" ] || (echo "::error::unexpected hash for sccdiff, possible tampering: $sccdiff_hash" && exit 1)
+          OUTPUT=$(cd pr && ../sccdiff -basedir ../base)
+          echo "${OUTPUT}"
+          OUTPUT="${OUTPUT//$'\n'/%0A}"
+          echo "::set-output name=diff::$OUTPUT"
+
+      - name: Comment Code Lines
+        continue-on-error: true
+        uses: marocchino/sticky-pull-request-comment@v2
         with:
-          args: ${{ env.workspace }} -M [.g.dart,.freezed.dart]
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          header: LOC
+          message: |
+            ### Lines Of Code
+
+            ${{ steps.loc.outputs.diff }}
